import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { usePageHeader } from '../../shared/context/PageHeaderContext';
import ReferralHeader from '../components/ReferralHeader';
import ReferralSubNav from '../components/ReferralSubNav';
import { Send, ClipboardList, Bot, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { useReferralDetail, useResolveReferral } from '../services/hooks';
import { useReferralTasks, useCompleteTask } from '../services/taskHooks';


function formatDate(iso) {
  if (!iso) return 'No date specified';
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

// Every task raised on this case so far - across ANY role, not just this
// one - so a case's full directive picture is visible in one place, same
// case-level visibility principle District Collector's cross-agency view
// already establishes as normal practice here.
// The "My Tasks" page this role used to have has been removed - a directive
// is only meaningful next to the case it concerns, so a directive raised FOR
// District Welfare Officer is completed here, in context, instead.
const ROLE_NAME = 'District Welfare Officer';

function CaseTasksList({ referralId }) {
  const query = useReferralTasks(referralId);
  const complete = useCompleteTask();
  const [completingId, setCompletingId] = useState(null);
  const [completeError, setCompleteError] = useState(null);
  const tasks = query.data?.tasks || [];

  const handleComplete = async (taskId) => {
    setCompleteError(null);
    setCompletingId(taskId);
    try {
      await complete.mutate(taskId);
      query.refetch();
    } catch (err) {
      setCompleteError(err.message || 'Could not update this directive. Kindly try again.');
    } finally {
      setCompletingId(null);
    }
  };

  if (query.loading) return <p className="text-xs text-gray-400">Loading...</p>;
  if (query.error) return <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{query.error}</div>;
  if (tasks.length === 0) return <p className="text-xs text-gray-400">No action items have been raised on this case yet.</p>;

  return (
    <div className="space-y-3">
      {completeError && <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{completeError}</div>}
      {tasks.map((t) => (
        <div key={t.taskId} className="border border-gray-200 rounded-lg p-3.5">
          <div className="flex items-center gap-2 flex-wrap mb-1.5">
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-brand-50 text-brand-900">{t.assignedToRole}</span>
            <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${t.status === 'Completed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{t.status}</span>
            {t.autoGenerated && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-700">
                <Bot size={10} /> System-Generated
              </span>
            )}
            {t.overdue && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-100 text-rose-700">
                <AlertTriangle size={10} /> Overdue
              </span>
            )}
          </div>
          <p className="text-xs text-gray-700">{t.action}</p>
          <p className="text-[10px] text-gray-400 mt-1.5">
            Assigned by {t.createdByName} on {formatDate(t.createdAt)} - Due: {formatDate(t.dueAt)}
            {t.completedAt && ` - Completed ${formatDate(t.completedAt)}`}
          </p>
          {t.assignedToRole === ROLE_NAME && t.status === 'Pending' && (
            <button
              onClick={() => handleComplete(t.taskId)}
              disabled={completingId === t.taskId}
              className="mt-2 flex items-center gap-1.5 px-3 py-1.5 border border-emerald-300 text-emerald-700 hover:bg-emerald-50 rounded-md text-[11px] font-semibold transition disabled:opacity-60"
            >
              <CheckCircle2 size={12} />
              {completingId === t.taskId ? 'Working...' : 'Mark Complete'}
            </button>
          )}
        </div>
      ))}
    </div>
  );
}

// No "Assign Action Item" here. This role delivers a service on a case - it
// has no statutory authority to direct another department. Under the PoA
// Act the district officer who CAN issue cross-departmental directives is
// the District Collector (district executive head, chair of the Act's own
// district-level vigilance and monitoring committee), and that role keeps
// this capability. The card and the backend POST /tasks behind it were
// inherited from the shared role template, not chosen for this role.
export default function ReferralTasks() {
  const { referralId } = useParams();
  const navigate = useNavigate();
  const [actionError, setActionError] = useState(null);
  const detailQuery = useReferralDetail(referralId);
  const resolve = useResolveReferral();
  const tasksQuery = useReferralTasks(referralId);

  usePageHeader({ title: 'Case Tasks' });

  const r = detailQuery.data;

  if (detailQuery.loading) {
    return <p className="text-sm text-gray-400">Loading...</p>;
  }
  if (detailQuery.error || !r) {
    return (
      <div className="bg-rose-50 border border-rose-200 text-rose-700 text-sm px-4 py-3 rounded-lg">
        {detailQuery.error || 'This referral could not be located.'}
      </div>
    );
  }

  const handleResolve = async () => {
    setActionError(null);
    try {
      await resolve.mutate(referralId);
      navigate('/dwo');
    } catch (err) {
      setActionError(err.message || 'Could not resolve this referral. Kindly try again.');
    }
  };

  return (
    <>
      <div className="space-y-4">
        <ReferralHeader r={r} backTo="/dwo" backLabel="Back to Referral Queue" onResolve={handleResolve} resolveLoading={resolve.loading} />
        <ReferralSubNav base={`/dwo/referrals/${referralId}`} />

        {actionError && <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-4 py-3 rounded-lg">{actionError}</div>}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 pt-2">
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white p-6 rounded-xl border border-gray-200/80 shadow-sm">
              <div className="flex items-center gap-1.5 mb-1">
                <CheckCircle2 size={15} className="text-brand-900" />
                <h3 className="font-bold text-sm text-gray-800">Action Items on This Case</h3>
              </div>
              <p className="text-[11px] text-gray-400 mb-4">Every directive raised on this case, whichever office it was assigned to.</p>
              <CaseTasksList referralId={referralId} />
            </div>
          </div>

          <div className="space-y-6">
          </div>
        </div>
      </div>
    </>
  );
}
