import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import StaffLayout from '../layouts/StaffLayout';
import ReferralHeader from '../components/ReferralHeader';
import ReferralSubNav from '../components/ReferralSubNav';
import { Send, ClipboardList, Bot, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { useReferralDetail, useResolveReferral } from '../services/hooks';
import { useReferralTasks, useCreateTask, useCompleteTask } from '../services/taskHooks';

// Roles a task may be assigned to - independent of this portal's own role,
// so a directive can be raised for any concerned office, not only this one.
const TASK_ASSIGNABLE_ROLES = [
  'District Welfare Officer', 'Investigating Officer', 'Protection Officer',
'DLSA Coordinator', 'District Collector', 'Rehabilitation Officer',
];

function formatDate(iso) {
  if (!iso) return 'No date specified';
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

// Every task raised on this case so far - across ANY role, not just this
// one - so a case's full directive picture is visible in one place, same
// case-level visibility principle District Collector's cross-agency view
// already establishes as normal practice here.
// The "My Tasks" page this role used to have has been removed - a directive
// is only meaningful next to the case it concerns, so a directive raised FOR
// District Welfare Officer is completed here, in context, instead.
const ROLE_NAME = 'District Welfare Officer';

function CaseTasksList({ referralId }) {
  const query = useReferralTasks(referralId);
  const complete = useCompleteTask();
  const [completingId, setCompletingId] = useState(null);
  const [completeError, setCompleteError] = useState(null);
  const tasks = query.data?.tasks || [];

  const handleComplete = async (taskId) => {
    setCompleteError(null);
    setCompletingId(taskId);
    try {
      await complete.mutate(taskId);
      query.refetch();
    } catch (err) {
      setCompleteError(err.message || 'Could not update this directive. Kindly try again.');
    } finally {
      setCompletingId(null);
    }
  };

  if (query.loading) return <p className="text-xs text-gray-400">Loading...</p>;
  if (query.error) return <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{query.error}</div>;
  if (tasks.length === 0) return <p className="text-xs text-gray-400">No action items have been raised on this case yet.</p>;

  return (
    <div className="space-y-3">
      {completeError && <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{completeError}</div>}
      {tasks.map((t) => (
        <div key={t.taskId} className="border border-gray-200 rounded-lg p-3.5">
          <div className="flex items-center gap-2 flex-wrap mb-1.5">
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-[#EBF4FA] text-[#3D5A80]">{t.assignedToRole}</span>
            <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${t.status === 'Completed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{t.status}</span>
            {t.autoGenerated && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-700">
                <Bot size={10} /> System-Generated
              </span>
            )}
            {t.overdue && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-100 text-rose-700">
                <AlertTriangle size={10} /> Overdue
              </span>
            )}
          </div>
          <p className="text-xs text-gray-700">{t.action}</p>
          <p className="text-[10px] text-gray-400 mt-1.5">
            Assigned by {t.createdByName} on {formatDate(t.createdAt)} - Due: {formatDate(t.dueAt)}
            {t.completedAt && ` - Completed ${formatDate(t.completedAt)}`}
          </p>
          {t.assignedToRole === ROLE_NAME && t.status === 'Pending' && (
            <button
              onClick={() => handleComplete(t.taskId)}
              disabled={completingId === t.taskId}
              className="mt-2 flex items-center gap-1.5 px-3 py-1.5 border border-emerald-300 text-emerald-700 hover:bg-emerald-50 rounded-md text-[11px] font-semibold transition disabled:opacity-60"
            >
              <CheckCircle2 size={12} />
              {completingId === t.taskId ? 'Working...' : 'Mark Complete'}
            </button>
          )}
        </div>
      ))}
    </div>
  );
}

function AssignTaskCard({ userId, referralId, onCreated }) {
  const [assignedToRole, setAssignedToRole] = useState(TASK_ASSIGNABLE_ROLES[0]);
  const [action, setAction] = useState('');
  const [dueAt, setDueAt] = useState('');
  const [error, setError] = useState(null);
  const [success, setSuccess] = useState(false);
  const createTask = useCreateTask();

  const handleSubmit = async () => {
    if (!action.trim()) return;
    setError(null);
    setSuccess(false);
    try {
      await createTask.mutate(userId, assignedToRole, action.trim(), dueAt ? new Date(dueAt).toISOString() : null, referralId);
      setAction('');
      setDueAt('');
      setSuccess(true);
      onCreated();
    } catch (err) {
      setError(err.message || 'Unable to assign this task. Kindly try again.');
    }
  };

  return (
    <div className="bg-white p-5 rounded-xl border border-gray-200/80 shadow-sm space-y-3">
      <div className="flex items-center gap-1.5">
        <ClipboardList size={15} className="text-[#3D5A80]" />
        <h3 className="font-bold text-sm text-gray-800">Assign Action Item</h3>
      </div>
      <p className="text-[11px] text-gray-400">Raise a structured, due-dated directive for any concerned office on this case.</p>
      <select
        value={assignedToRole}
        onChange={(e) => setAssignedToRole(e.target.value)}
        className="w-full px-3 py-2 border border-gray-300 rounded-lg text-xs"
      >
        {TASK_ASSIGNABLE_ROLES.map((role) => <option key={role} value={role}>{role}</option>)}
      </select>
      <textarea
        value={action}
        onChange={(e) => setAction(e.target.value)}
        placeholder="Specify the action required..."
        rows={3}
        className="w-full px-3 py-2 border border-gray-300 rounded-lg text-xs"
      />
      <div>
        <label className="text-[10px] font-bold text-gray-500 uppercase block mb-1">Due Date</label>
        <input
          type="date"
          value={dueAt}
          onChange={(e) => setDueAt(e.target.value)}
          className="w-full px-3 py-2 border border-gray-300 rounded-lg text-xs"
        />
      </div>
      <button
        onClick={handleSubmit}
        disabled={!action.trim() || createTask.loading}
        className="w-full flex items-center justify-center gap-1.5 px-3 py-2.5 bg-[#3D5A80] hover:bg-[#2f4763] text-white rounded-lg text-xs font-semibold transition disabled:opacity-60"
      >
        <Send size={13} />
        {createTask.loading ? 'Submitting...' : 'Submit'}
      </button>
      {error && <p className="text-xs text-rose-600">{error}</p>}
      {success && <p className="text-xs text-emerald-600">Action item assigned successfully.</p>}
    </div>
  );
}

export default function ReferralTasks() {
  const { referralId } = useParams();
  const navigate = useNavigate();
  const [actionError, setActionError] = useState(null);
  const detailQuery = useReferralDetail(referralId);
  const resolve = useResolveReferral();
  const tasksQuery = useReferralTasks(referralId);

  const r = detailQuery.data;

  if (detailQuery.loading) {
    return <StaffLayout title="Case Tasks"><p className="text-sm text-gray-400">Loading...</p></StaffLayout>;
  }
  if (detailQuery.error || !r) {
    return (
      <StaffLayout title="Case Tasks">
        <div className="bg-rose-50 border border-rose-200 text-rose-700 text-sm px-4 py-3 rounded-lg">
          {detailQuery.error || 'This referral could not be located.'}
        </div>
      </StaffLayout>
    );
  }

  const handleResolve = async () => {
    setActionError(null);
    try {
      await resolve.mutate(referralId);
      navigate('/dwo');
    } catch (err) {
      setActionError(err.message || 'Could not resolve this referral. Kindly try again.');
    }
  };

  return (
    <StaffLayout title="Case Tasks">
      <div className="space-y-4">
        <ReferralHeader r={r} backTo="/dwo" backLabel="Back to Referral Queue" onResolve={handleResolve} resolveLoading={resolve.loading} />
        <ReferralSubNav base={`/dwo/referrals/${referralId}`} />

        {actionError && <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-4 py-3 rounded-lg">{actionError}</div>}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 pt-2">
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white p-6 rounded-xl border border-gray-200/80 shadow-sm">
              <div className="flex items-center gap-1.5 mb-1">
                <CheckCircle2 size={15} className="text-[#3D5A80]" />
                <h3 className="font-bold text-sm text-gray-800">Action Items on This Case</h3>
              </div>
              <p className="text-[11px] text-gray-400 mb-4">Every directive raised on this case, whichever office it was assigned to.</p>
              <CaseTasksList referralId={referralId} />
            </div>
          </div>

          <div className="space-y-6">
            {r.status === 'Open' && <AssignTaskCard userId={r.userId} referralId={referralId} onCreated={tasksQuery.refetch} />}
          </div>
        </div>
      </div>
    </StaffLayout>
  );
}
