import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import StaffLayout from '../layouts/StaffLayout';
import { CheckCircle2, AlertTriangle, Bot, ArrowRight } from 'lucide-react';
import { useTasksList, useCompleteTask } from '../services/taskHooks';

// This role's own name - a task's source referral only opens a "View
// Referral" link when it actually belongs to this portal's own queue (see
// spp.routes.js's GET /tasks comment on sourceReferralRole).
const ROLE_NAME = 'Special Public Prosecutor';

// Special Public Prosecutor's My Tasks - structured action items assigned
// to this role (migration_030_agency_tasks.sql), each with a specific
// action and due date, rather than a free-text remark only visible if the
// reader happens upon it. Mirrors dwo/pages/MyTasks.jsx (the template).
// Formal register throughout, per instruction - this is a government
// case-management portal, not a consumer app.

function formatDate(iso) {
  if (!iso) return 'No date specified';
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function TaskRow({ t, onChanged }) {
  const navigate = useNavigate();
  const complete = useCompleteTask();
  const [error, setError] = useState(null);
  const canOpenReferral = t.sourceReferralId && t.sourceReferralRole === ROLE_NAME;

  const handleComplete = async () => {
    setError(null);
    try {
      await complete.mutate(t.taskId);
      onChanged();
    } catch (err) {
      setError(err.message || 'Unable to update this task. Kindly try again.');
    }
  };

  return (
    <div className="px-6 py-4">
      <div className="flex items-start justify-between gap-3">
        <div className="min-w-0">
          <div className="flex items-center gap-2 flex-wrap mb-1">
            <p className="text-sm font-bold text-gray-800">{t.docketNumber}</p>
            {t.autoGenerated && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-700">
                <Bot size={10} /> System-Generated
              </span>
            )}
            {t.overdue && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-100 text-rose-700">
                <AlertTriangle size={10} /> Overdue
              </span>
            )}
          </div>
          <p className="text-xs text-gray-500 mb-1">{t.caseTypeName}</p>
          <p className="text-sm text-gray-700">{t.action}</p>
          <p className="text-[11px] text-gray-400 mt-1.5">
            Assigned by {t.createdByName} on {formatDate(t.createdAt)} - Due: {formatDate(t.dueAt)}
          </p>
        </div>
        <div className="flex flex-col items-end gap-2 shrink-0">
          {canOpenReferral && (
            <button
              onClick={() => navigate(`/spp/referrals/${t.sourceReferralId}`)}
              className="flex items-center gap-1.5 px-3 py-1.5 border border-[#519BCE] text-[#519BCE] hover:bg-[#519BCE] hover:text-white rounded-md text-[11px] font-semibold transition"
            >
              View Referral <ArrowRight size={12} />
            </button>
          )}
          {t.status === 'Pending' && (
            <button
              onClick={handleComplete}
              disabled={complete.loading}
              className="flex items-center gap-1.5 px-3 py-1.5 border border-emerald-300 text-emerald-700 hover:bg-emerald-50 rounded-md text-[11px] font-semibold transition disabled:opacity-60"
            >
              <CheckCircle2 size={13} />
              {complete.loading ? 'Updating...' : 'Mark as Completed'}
            </button>
          )}
        </div>
      </div>
      {error && <div className="mt-2 bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{error}</div>}
    </div>
  );
}

export default function MyTasks() {
  const [tab, setTab] = useState('Pending');
  const query = useTasksList(tab);
  const tasks = query.data?.tasks || [];

  return (
    <StaffLayout title="My Tasks">
      <div className="space-y-4">
        <div className="bg-white p-4 rounded-xl border border-gray-200/80 shadow-sm space-y-4">
          <div>
            <h3 className="font-bold text-sm text-gray-800">Assigned Action Items</h3>
            <p className="text-[11px] text-gray-400">Tasks assigned to this office, including those raised automatically upon prolonged inaction on a referral. Kindly action Pending items before the stated due date.</p>
          </div>

          <div className="flex flex-wrap gap-2">
            {['Pending', 'Completed'].map((s) => (
              <button
                key={s}
                onClick={() => setTab(s)}
                className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold transition ${
                  tab === s ? 'bg-[#519BCE] text-white shadow-sm' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
                }`}
              >
                {s}
              </button>
            ))}
          </div>

          <div className="border border-gray-200/80 rounded-xl overflow-hidden">
            {query.loading ? (
              <p className="text-sm text-gray-400 p-6">Loading, please wait...</p>
            ) : query.error ? (
              <div className="bg-rose-50 border border-rose-200 text-rose-700 text-sm px-4 py-3 m-4 rounded-lg">{query.error}</div>
            ) : tasks.length === 0 ? (
              <p className="text-sm text-gray-400 p-6">No {tab.toLowerCase()} action items at this time.</p>
            ) : (
              <div className="divide-y divide-gray-100">
                {tasks.map((t) => (
                  <TaskRow key={t.taskId} t={t} onChanged={query.refetch} />
                ))}
              </div>
            )}
          </div>
        </div>
      </div>
    </StaffLayout>
  );
}
