-- migration_012_rename_victim_to_user.sql
-- Description: Renames every "victim" table/column/index/policy to "user",
-- as part of the role-based restructure (Victim -> User across backend,
-- frontend, and DB). Pure renames only - no data is dropped or altered,
-- and every FK relationship survives the rename intact (Postgres tracks
-- constraints by OID, not by name).

BEGIN;

-- 1. Core tables
ALTER TABLE victims RENAME TO users;
ALTER TABLE users RENAME COLUMN victim_id TO user_id;

ALTER TABLE victim_identity RENAME TO user_identity;
ALTER TABLE user_identity RENAME COLUMN victim_id TO user_id;

ALTER TABLE victim_questionnaires RENAME TO user_questionnaires;
ALTER TABLE user_questionnaires RENAME COLUMN victim_id TO user_id;

-- 2. FK column on every other table that references victims/users
ALTER TABLE consent_records RENAME COLUMN victim_id TO user_id;
ALTER TABLE interactions RENAME COLUMN victim_id TO user_id;
ALTER TABLE distress_scores RENAME COLUMN victim_id TO user_id;
ALTER TABLE alerts RENAME COLUMN victim_id TO user_id;
ALTER TABLE sos_events RENAME COLUMN victim_id TO user_id;
ALTER TABLE interventions RENAME COLUMN victim_id TO user_id;
ALTER TABLE case_notes RENAME COLUMN victim_id TO user_id;
ALTER TABLE dispatch_queue RENAME COLUMN victim_id TO user_id;
ALTER TABLE audit_log RENAME COLUMN victim_id TO user_id;
ALTER TABLE chat_messages RENAME COLUMN victim_id TO user_id;
ALTER TABLE messages RENAME COLUMN victim_id TO user_id;
ALTER TABLE journal_entries RENAME COLUMN victim_id TO user_id;
ALTER TABLE counselling_sessions RENAME COLUMN victim_id TO user_id;

-- 3. Named indexes that encode "victim" in their own name (constraint/PK/FK
-- names auto-generated by Postgres, e.g. victims_pkey, are left as-is -
-- renaming a table/column does not rename them, and leaving them alone
-- avoids any risk of a name collision; they are never referenced by name
-- anywhere in application code).
ALTER INDEX idx_victims_jurisdiction RENAME TO idx_users_jurisdiction;
ALTER INDEX idx_interactions_victim RENAME TO idx_interactions_user;
ALTER INDEX idx_distress_scores_victim RENAME TO idx_distress_scores_user;
ALTER INDEX idx_sos_events_victim RENAME TO idx_sos_events_user;
ALTER INDEX idx_audit_log_victim RENAME TO idx_audit_log_user;
ALTER INDEX idx_case_notes_victim RENAME TO idx_case_notes_user;
ALTER INDEX idx_chat_messages_victim RENAME TO idx_chat_messages_user;
ALTER INDEX idx_messages_victim RENAME TO idx_messages_user;
ALTER INDEX idx_journal_entries_victim RENAME TO idx_journal_entries_user;

-- 4. RLS policies on user_questionnaires (drop + recreate under the new
-- table/column names; policy text also renamed for consistency).
DROP POLICY IF EXISTS "Victims can insert their own questionnaires" ON user_questionnaires;
DROP POLICY IF EXISTS "Victims can read their own questionnaires" ON user_questionnaires;
DROP POLICY IF EXISTS "Staff can read all questionnaires" ON user_questionnaires;

CREATE POLICY "Users can insert their own questionnaires"
    ON user_questionnaires
    FOR INSERT
    WITH CHECK (user_id = (current_setting('request.jwt.claims', true)::json->>'sub')::uuid);

CREATE POLICY "Users can read their own questionnaires"
    ON user_questionnaires
    FOR SELECT
    USING (user_id = (current_setting('request.jwt.claims', true)::json->>'sub')::uuid);

CREATE POLICY "Staff can read all questionnaires"
    ON user_questionnaires
    FOR SELECT
    USING (
        (current_setting('request.jwt.claims', true)::json->>'account_type') IN ('Counsellor', 'Administration', 'Ministry')
    );

COMMIT;

-- 5. The 'victim' string literal also appears as a CHECK-constrained enum
-- value (not just a table/column name) on two chat-role columns. No existing
-- rows used it at migration time, so this is a pure constraint edit, not a
-- data backfill - if that's no longer true when this runs, add an
-- `UPDATE ... SET sender = 'user' WHERE sender = 'victim'` (and the
-- sender_type equivalent) before the ALTER TABLE ... DROP CONSTRAINT below.
BEGIN;
ALTER TABLE chat_messages DROP CONSTRAINT chat_messages_sender_check;
ALTER TABLE chat_messages ADD CONSTRAINT chat_messages_sender_check CHECK (sender IN ('user', 'ai'));
ALTER TABLE messages DROP CONSTRAINT messages_sender_type_check;
ALTER TABLE messages ADD CONSTRAINT messages_sender_type_check CHECK (sender_type IN ('user', 'official'));
COMMIT;
