import React, { useState } from 'react';
import { useParams } from 'react-router-dom';
import { usePageHeader } from '../../shared/context/PageHeaderContext';
import CaseHeader from '../components/CaseHeader';
import CaseSubNav from '../components/CaseSubNav';
import { Bot, AlertTriangle, CheckCircle2 } from 'lucide-react';
import { useCaseDetail, useCaseTasks, useMarkInvestigationComplete, useCompleteDirective } from '../services/hooks';

// Read-only, except for completing a directive raised FOR this role.
// Investigating Officer has no authority to raise cross-departmental
// directives - IO's own statutory function (Rule 7, PoA Rules) is
// investigation (arrest, custody, chargesheet); directing another
// department is an executive act belonging to District Collector. The
// "Assign Action Item" card that used to sit here has been removed, along
// with the backend's own POST /tasks for this role.
const ROLE_NAME = 'Investigating Officer';

function formatDate(iso) {
  if (!iso) return 'No date specified';
  return new Date(iso).toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' });
}

function CaseTasksList({ userId, onChanged }) {
  const query = useCaseTasks(userId);
  const complete = useCompleteDirective();
  const [completingId, setCompletingId] = useState(null);
  const [error, setError] = useState(null);
  const tasks = query.data?.tasks || [];

  if (query.loading) return <p className="text-xs text-gray-400">Loading...</p>;
  if (query.error) return <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{query.error}</div>;
  if (tasks.length === 0) return <p className="text-xs text-gray-400">No action items have been raised on this case yet.</p>;

  const handleComplete = async (taskId) => {
    setError(null);
    setCompletingId(taskId);
    try {
      await complete.mutate(taskId);
      query.refetch();
      onChanged?.();
    } catch (err) {
      setError(err.message || 'Could not update this directive. Kindly try again.');
    } finally {
      setCompletingId(null);
    }
  };

  return (
    <div className="space-y-3">
      {error && <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-3 py-2 rounded-lg">{error}</div>}
      {tasks.map((t) => (
        <div key={t.taskId} className="border border-gray-200 rounded-lg p-3.5">
          <div className="flex items-center gap-2 flex-wrap mb-1.5">
            <span className="px-2 py-0.5 rounded-full text-[10px] font-bold bg-brand-50 text-brand-900">{t.assignedToRole}</span>
            <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${t.status === 'Completed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-700'}`}>{t.status}</span>
            {t.autoGenerated && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-indigo-100 text-indigo-700">
                <Bot size={10} /> System-Generated
              </span>
            )}
            {t.overdue && (
              <span className="flex items-center gap-1 px-2 py-0.5 rounded-full text-[10px] font-bold bg-rose-100 text-rose-700">
                <AlertTriangle size={10} /> Overdue
              </span>
            )}
          </div>
          <p className="text-xs text-gray-700">{t.action}</p>
          <p className="text-[10px] text-gray-400 mt-1.5">
            Assigned by {t.createdByName} on {formatDate(t.createdAt)} - Due: {formatDate(t.dueAt)}
            {t.completedAt && ` - Completed ${formatDate(t.completedAt)}`}
          </p>
          {/* Only a directive raised FOR this role can be closed out here. */}
          {t.assignedToRole === ROLE_NAME && t.status === 'Pending' && (
            <button
              onClick={() => handleComplete(t.taskId)}
              disabled={completingId === t.taskId}
              className="mt-2 flex items-center gap-1.5 px-3 py-1.5 border border-emerald-300 text-emerald-700 hover:bg-emerald-50 rounded-md text-[11px] font-semibold transition disabled:opacity-60"
            >
              <CheckCircle2 size={12} />
              {completingId === t.taskId ? 'Working...' : 'Mark Complete'}
            </button>
          )}
        </div>
      ))}
    </div>
  );
}

export default function CaseTasks() {
  const { userId } = useParams();
  const [actionError, setActionError] = useState(null);
  const detailQuery = useCaseDetail(userId);
  const tasksQuery = useCaseTasks(userId);
  const markComplete = useMarkInvestigationComplete();

  usePageHeader({ title: 'Case Tasks' });

  const c = detailQuery.data;

  if (detailQuery.loading) {
    return <p className="text-sm text-gray-400">Loading...</p>;
  }
  if (detailQuery.error || !c) {
    return (
      <div className="bg-rose-50 border border-rose-200 text-rose-700 text-sm px-4 py-3 rounded-lg">
        {detailQuery.error || 'This case could not be located.'}
      </div>
    );
  }

  const handleMarkComplete = async () => {
    setActionError(null);
    try {
      await markComplete.mutate(userId);
      detailQuery.refetch();
    } catch (err) {
      setActionError(err.message || 'Could not mark investigation complete. Kindly try again.');
    }
  };

  return (
    <>
      <div className="space-y-4">
        <CaseHeader c={c} backTo="/io" backLabel="Back to Case Queue" onMarkComplete={handleMarkComplete} markCompleteLoading={markComplete.loading} />
        <CaseSubNav base={`/io/cases/${userId}`} />

        {actionError && <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-4 py-3 rounded-lg">{actionError}</div>}

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-6 pt-2">
          <div className="lg:col-span-2 space-y-6">
            <div className="bg-white p-6 rounded-xl border border-gray-200/80 shadow-sm">
              <div className="flex items-center gap-1.5 mb-1">
                <CheckCircle2 size={15} className="text-brand-900" />
                <h3 className="font-bold text-sm text-gray-800">Action Items on This Case</h3>
              </div>
              <p className="text-[11px] text-gray-400 mb-4">Every directive raised on this case, whichever office it was assigned to.</p>
              <CaseTasksList userId={userId} onChanged={tasksQuery.refetch} />
            </div>
          </div>

        </div>
      </div>
    </>
  );
}
