const { pool } = require('../db/pgPool');
const { supabase } = require('../db/supabaseClient');
const { writeAuditLog } = require('./auditLog');
const { ensureCourtCaseDetails } = require('./courtCaseSync');

// migration_045 - makes NHaa's own case_stage a genuine DERIVATIVE of the
// real (simulated) eCourt record, instead of the inversion this file used
// to be: previously, case_stage was just a bare timer
// (STAGE_INTERVAL_MS-driven, no real fact behind it) and court_case_details
// was generated FROM that timer's own value - i.e. "eCourt" was downstream
// of NHaa, backwards from how it actually works. Now:
//
//   - Investigation -> Trial fires on a real, already-tracked fact: the
//     Investigating Officer's own chargesheet_status reaching 'Filed'
//     (investigation_records - migration_033). A chargesheet being filed IS
//     what moves a matter from police investigation into court in real
//     life, so this needed no new fact of its own to track.
//   - Trial -> Compensation fires once the case's own REAL (simulated)
//     eCourt record - court_case_details.case_status, generated by
//     courtCaseSimulation.js entirely independently of case_stage now -
//     reaches 'Disposed'. This is the actual "eCourt made an update"
//     requirement 8/case-stage-split asked for: eCourt disposes the case on
//     its own clock (TRIAL_DISPOSAL_AFTER_DAYS), NHaa's stage just follows.
//
// case_stage now only ever holds 3 values (Investigation/Trial/
// Compensation) - Rehabilitation is not a stage any more (it's a
// person-level opt-in fact, triggered once a case reaches Compensation -
// see rehabilitationStatus.js) and neither is "Case Closed" (a case's own
// end is now case_completed_at, an access fact computed by
// caseCompletion.js once compensation and rehabilitation are both
// resolved - not a place a case procedurally "is").
const STAGE_SEQUENCE = ['Investigation', 'Trial', 'Compensation'];

function getNextStage(currentStage) {
  const idx = STAGE_SEQUENCE.indexOf(currentStage);
  if (idx === -1 || idx === STAGE_SEQUENCE.length - 1) return null; // unknown or already terminal
  return STAGE_SEQUENCE[idx + 1];
}

async function advanceInvestigationToTrial() {
  const { rows } = await pool.query(
    `select u.user_id from users u
     join investigation_records ir on ir.user_id = u.user_id
     where u.case_stage = 'Investigation' and ir.chargesheet_status = 'Filed'`
  );
  let advanced = 0;
  for (const row of rows) {
    const { error } = await supabase.from('users').update({ case_stage: 'Trial' }).eq('user_id', row.user_id);
    if (error) {
      console.error('advanceInvestigationToTrial: could not update case_stage', error.message, { userId: row.user_id });
      continue;
    }
    await writeAuditLog({ userId: row.user_id, action: 'update', entityType: 'ecourt_case_stage', entityId: row.user_id, details: { fromStage: 'Investigation', toStage: 'Trial', note: 'Chargesheet filed' } });
    console.log(`eCourt sync: ${row.user_id} advanced Investigation -> Trial (chargesheet filed)`);
    advanced += 1;
  }
  return advanced;
}

async function advanceTrialToCompensation() {
  const { rows } = await pool.query(
    `select u.user_id, u.docket_number, u.case_stage, u.cnr_number, u.enrolled_at,
            ct.name as case_type_name, j.name as jurisdiction_name, ui.full_name as victim_full_name
     from users u
     join case_types ct on ct.case_type_id = u.case_type_id
     left join jurisdictions j on j.jurisdiction_id = u.jurisdiction_id
     left join user_identity ui on ui.user_id = coalesce(u.linked_to_user_id, u.user_id)
     where u.case_stage = 'Trial'`
  );

  let advanced = 0;
  for (const row of rows) {
    let courtCase;
    try {
      courtCase = await ensureCourtCaseDetails({
        userId: row.user_id,
        caseStage: row.case_stage,
        docketNumber: row.docket_number,
        cnrNumber: row.cnr_number,
        caseTypeName: row.case_type_name,
        jurisdictionName: row.jurisdiction_name,
        enrolledAt: row.enrolled_at,
        victimFullName: row.victim_full_name,
      });
    } catch (err) {
      console.error('advanceTrialToCompensation: could not load court case details', err.message, { userId: row.user_id });
      continue;
    }
    if (!courtCase.available || courtCase.row.case_status !== 'Disposed') continue;

    const { error } = await supabase.from('users').update({ case_stage: 'Compensation' }).eq('user_id', row.user_id);
    if (error) {
      console.error('advanceTrialToCompensation: could not update case_stage', error.message, { userId: row.user_id });
      continue;
    }
    await writeAuditLog({ userId: row.user_id, action: 'update', entityType: 'ecourt_case_stage', entityId: row.user_id, details: { fromStage: 'Trial', toStage: 'Compensation', note: `eCourt disposed the case (${courtCase.row.disposal_nature || 'outcome pending record'})` } });
    console.log(`eCourt sync: ${row.user_id} advanced Trial -> Compensation (eCourt disposed the case)`);
    advanced += 1;
  }
  return advanced;
}

async function runECourtSyncTick() {
  const toTrial = await advanceInvestigationToTrial();
  const toCompensation = await advanceTrialToCompensation();
  return toTrial + toCompensation;
}

function startECourtSyncWorker(intervalMs = 30 * 1000) {
  const tick = async () => {
    try {
      const count = await runECourtSyncTick();
      if (count) console.log(`eCourt sync: ${count} case(s) advanced this tick.`);
    } catch (err) {
      console.error('eCourt sync tick failed:', err.message);
    }
  };
  tick();
  return setInterval(tick, intervalMs);
}

module.exports = { STAGE_SEQUENCE, getNextStage, runECourtSyncTick, startECourtSyncWorker };
