import React, { useMemo, useState } from 'react';
import { usePageHeader } from '../../shared/context/PageHeaderContext';
import { Download, FilePlus, ChevronDown, ChevronUp, CheckCircle2, Forward } from 'lucide-react';
import {
  useMyJurisdiction, useReportsList, useUpdateReportStatus, useDownloadReportPdf, useForwardReport,
} from '../services/hooks';
import GenerateReportModal from '../components/GenerateReportModal';
import ReportSnapshotView, { RecipientPills } from '../components/ReportSnapshotView';

// National Admin's real state-wise report generate/submit/review workflow -
// Generate Report modal + My Reports Inbox/Outbox. The read-only analytics
// this page used to also carry (trend/severity/intervention charts, CSV
// export, stat cards) moved into the Analysis page, alongside the existing
// cross-state comparison bars - that's analysis of National's ongoing
// caseload, not part of the periodic report record National actually shares
// with Ministry, and didn't belong mixed into this page.

const REPORT_STATUS_BADGE = {
  Draft: 'bg-gray-100 text-gray-600',
  Submitted: 'bg-amber-100 text-amber-700',
  Reviewed: 'bg-emerald-100 text-emerald-700',
};

// National has nothing to forward TO except Ministry - it's the top of the
// jurisdiction chain, Ministry is the only tier above it.
const FORWARD_TARGETS = [{ label: 'Ministry', type: 'ministry' }];

// Inbox can hold BOTH District-tier reports (cc'd or forwarded directly,
// bypassing State) and State-tier reports (the normal primary-recipient
// flow) at once - grouping by origin tier, not one flat list, is what makes
// that legible (mirrors Ministry's own equivalent grouping).
const TIER_GROUP_LABELS = {
  district: 'From Districts (Direct)',
  state: 'From States',
  national: 'From National',
};
const TIER_GROUP_ORDER = ['state', 'district', 'national'];

function ReportRow({ r, box, onMarkReviewed, markingId, onDownload, downloadingId, forwardTargets, onForward, forwardingId }) {
  const [expanded, setExpanded] = useState(false);
  const [showForwardMenu, setShowForwardMenu] = useState(false);
  const canReview = box === 'inbox' && r.myStatus !== 'Reviewed';
  const canForward = box === 'inbox';

  return (
    <div>
      <button
        onClick={() => setExpanded((v) => !v)}
        className="w-full flex items-center justify-between px-6 py-4 text-left hover:bg-gray-50/70 transition gap-3"
      >
        <div className="min-w-0">
          <div className="flex items-center gap-2 flex-wrap">
            <p className="text-sm font-bold text-gray-800">{r.jurisdictionName || r.jurisdictionId}</p>
            {r.status && (
              <span className={`px-2 py-0.5 rounded-full text-[10px] font-bold ${REPORT_STATUS_BADGE[r.status] || 'bg-gray-100 text-gray-600'}`}>{r.status}</span>
            )}
            {r.periodLabel && <span className="text-[10px] text-gray-400">{r.periodLabel}</span>}
          </div>
          <p className="text-xs text-gray-500">Generated by {r.generatedByName || 'Unknown'} - {r.generatedAt ? new Date(r.generatedAt).toLocaleString() : '-'}</p>
        </div>
        <div className="flex items-center gap-2 shrink-0">
          <span
            role="button"
            tabIndex={0}
            onClick={(e) => { e.stopPropagation(); onDownload(r.reportId, `${r.jurisdictionName || 'report'}_${r.periodLabel || ''}`.trim()); }}
            onKeyDown={(e) => { if (e.key === 'Enter') { e.stopPropagation(); onDownload(r.reportId, r.jurisdictionName || 'report'); } }}
            className="flex items-center gap-1.5 px-3 py-1.5 border border-gray-300 text-gray-600 hover:bg-gray-50 rounded-md text-[11px] font-semibold transition"
          >
            <Download size={13} />
            {downloadingId === r.reportId ? 'Downloading...' : 'PDF'}
          </span>
          {canReview && (
            <span
              role="button"
              tabIndex={0}
              onClick={(e) => { e.stopPropagation(); onMarkReviewed(r.reportId); }}
              onKeyDown={(e) => { if (e.key === 'Enter') { e.stopPropagation(); onMarkReviewed(r.reportId); } }}
              className="flex items-center gap-1.5 px-3 py-1.5 border border-emerald-300 text-emerald-700 hover:bg-emerald-50 rounded-md text-[11px] font-semibold transition"
            >
              <CheckCircle2 size={13} />
              {markingId === r.reportId ? 'Marking...' : 'Mark Reviewed'}
            </span>
          )}
          {canForward && forwardTargets.length > 0 && (
            <div className="relative">
              <span
                role="button"
                tabIndex={0}
                onClick={(e) => { e.stopPropagation(); setShowForwardMenu((v) => !v); }}
                onKeyDown={(e) => { if (e.key === 'Enter') { e.stopPropagation(); setShowForwardMenu((v) => !v); } }}
                className="flex items-center gap-1.5 px-3 py-1.5 border border-gray-300 text-gray-600 hover:bg-gray-50 rounded-md text-[11px] font-semibold transition"
              >
                <Forward size={13} />
                {forwardingId === r.reportId ? 'Forwarding...' : 'Forward'}
              </span>
              {showForwardMenu && (
                <div
                  onClick={(e) => e.stopPropagation()}
                  className="absolute right-0 top-full mt-1 bg-white border border-gray-200 rounded-lg shadow-lg py-1 z-10 min-w-[160px]"
                >
                  {forwardTargets.map((t) => (
                    <button
                      key={t.label}
                      onClick={() => { setShowForwardMenu(false); onForward(r.reportId, t); }}
                      className="w-full text-left px-3 py-2 text-xs text-gray-700 hover:bg-gray-50 transition"
                    >
                      {t.label}
                    </button>
                  ))}
                </div>
              )}
            </div>
          )}
          {expanded ? <ChevronUp size={18} className="text-gray-400" /> : <ChevronDown size={18} className="text-gray-400" />}
        </div>
      </button>
      {expanded && (
        <div className="px-6 pb-5 text-xs text-gray-600 space-y-4">
          {r.commentary && (
            <div className="bg-brand-50/60 border border-brand-100 rounded-lg p-3">
              <p className="font-bold text-brand-900 text-[11px] uppercase mb-1">Commentary</p>
              <p className="whitespace-pre-wrap">{r.commentary}</p>
            </div>
          )}
          <ReportSnapshotView snapshot={r.snapshot} />
          {r.recipients && r.recipients.length > 0 && (
            <div>
              <p className="text-[11px] font-bold text-gray-500 uppercase mb-1.5">Recipients</p>
              <RecipientPills recipients={r.recipients} />
            </div>
          )}
        </div>
      )}
    </div>
  );
}

export default function Reports() {
  usePageHeader({ title: 'State-Wise Reports' });
  const { jurisdictionId } = useMyJurisdiction();

  const [reportsTab, setReportsTab] = useState('inbox');
  const [showGenerateModal, setShowGenerateModal] = useState(false);
  const [markingId, setMarkingId] = useState(null);
  const [downloadingId, setDownloadingId] = useState(null);
  const [forwardingId, setForwardingId] = useState(null);
  const [reportsActionError, setReportsActionError] = useState(null);

  const inboxQuery = useReportsList(jurisdictionId, 'inbox');
  const outboxQuery = useReportsList(jurisdictionId, 'outbox');
  const updateReportStatus = useUpdateReportStatus();
  const downloadReportPdf = useDownloadReportPdf();
  const forwardReport = useForwardReport();

  const inboxReports = inboxQuery.data?.reports || [];
  const outboxReports = outboxQuery.data?.reports || [];
  const activeReportsQuery = reportsTab === 'inbox' ? inboxQuery : outboxQuery;
  const visibleReports = reportsTab === 'inbox' ? inboxReports : outboxReports;

  // Group the Inbox by origin tier (District-direct vs State, the normal
  // flow) - a flat list mixing case-wise-origin and district-wise-origin
  // reports together reads as a jumble; Outbox is always all-one-tier
  // (National's own generated reports), so it stays a plain list.
  const groupedInbox = useMemo(() => {
    if (reportsTab !== 'inbox') return null;
    const byTier = new Map();
    for (const r of inboxReports) {
      const tier = r.tier || 'state';
      if (!byTier.has(tier)) byTier.set(tier, []);
      byTier.get(tier).push(r);
    }
    return TIER_GROUP_ORDER
      .filter((tier) => byTier.has(tier))
      .map((tier) => ({ tier, label: TIER_GROUP_LABELS[tier] || tier, reports: byTier.get(tier) }));
  }, [reportsTab, inboxReports]);

  const handleReportGenerated = () => {
    inboxQuery.refetch();
    outboxQuery.refetch();
  };

  const handleMarkReviewed = async (reportId) => {
    setReportsActionError(null);
    setMarkingId(reportId);
    try {
      await updateReportStatus.mutate(reportId, 'Reviewed');
      inboxQuery.refetch();
    } catch (err) {
      setReportsActionError(err.message || 'Could not update report status.');
    } finally {
      setMarkingId(null);
    }
  };

  const handleDownloadPdf = async (reportId, name) => {
    setReportsActionError(null);
    setDownloadingId(reportId);
    try {
      await downloadReportPdf.mutate(reportId, name);
    } catch (err) {
      setReportsActionError(err.message || 'Could not download PDF.');
    } finally {
      setDownloadingId(null);
    }
  };

  const handleForward = async (reportId, target) => {
    setReportsActionError(null);
    setForwardingId(reportId);
    try {
      await forwardReport.mutate(reportId, target);
      inboxQuery.refetch();
    } catch (err) {
      setReportsActionError(err.message || 'Could not forward report.');
    } finally {
      setForwardingId(null);
    }
  };

  return (
    <>
      <div className="space-y-6">

        {/* STATE-WISE REPORTS: Generate + My Reports (Inbox/Outbox) */}
        <div className="bg-white p-4 rounded-xl border border-gray-200/80 shadow-sm space-y-4">
          <div className="flex flex-wrap items-center justify-between gap-3">
            <div>
              <h3 className="font-bold text-sm text-gray-800">State-Wise Reports</h3>
              <p className="text-[11px] text-gray-400">Generate a state-wise rollup report and submit it to Ministry.</p>
            </div>
            <button
              onClick={() => setShowGenerateModal(true)}
              className="flex items-center gap-2 px-4 py-2 bg-brand-700 hover:bg-brand-800 text-white rounded-lg text-xs font-semibold shadow-sm transition"
            >
              <FilePlus size={14} />
              Generate Report
            </button>
          </div>

          <div className="flex flex-wrap gap-2">
            <button
              onClick={() => setReportsTab('inbox')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold transition ${
                reportsTab === 'inbox' ? 'bg-brand-700 text-white shadow-sm' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
              }`}
            >
              Inbox {inboxReports.length > 0 ? `(${inboxReports.length})` : ''}
            </button>
            <button
              onClick={() => setReportsTab('outbox')}
              className={`px-3.5 py-1.5 rounded-lg text-xs font-semibold transition ${
                reportsTab === 'outbox' ? 'bg-brand-700 text-white shadow-sm' : 'bg-white text-gray-600 border border-gray-200 hover:bg-gray-50'
              }`}
            >
              Outbox {outboxReports.length > 0 ? `(${outboxReports.length})` : ''}
            </button>
          </div>

          {reportsActionError && (
            <div className="bg-rose-50 border border-rose-200 text-rose-700 text-xs px-4 py-2.5 rounded-lg">{reportsActionError}</div>
          )}

          <div className="border border-gray-200/80 rounded-xl overflow-hidden">
            {activeReportsQuery.loading ? (
              <p className="text-sm text-gray-400 p-6">Loading...</p>
            ) : activeReportsQuery.error ? (
              <div className="bg-rose-50 border border-rose-200 text-rose-700 text-sm px-4 py-3 m-4 rounded-lg">{activeReportsQuery.error}</div>
            ) : visibleReports.length === 0 ? (
              <p className="text-sm text-gray-400 p-6">
                {reportsTab === 'inbox' ? 'No reports received yet.' : 'No reports generated yet.'}
              </p>
            ) : groupedInbox ? (
              <div className="divide-y divide-gray-200">
                {groupedInbox.map((group) => (
                  <div key={group.tier}>
                    <p className="px-6 pt-3 pb-1 text-[10px] font-bold uppercase tracking-wide text-gray-400 bg-gray-50/60">{group.label}</p>
                    <div className="divide-y divide-gray-100">
                      {group.reports.map((r) => (
                        <ReportRow
                          key={r.reportId}
                          r={r}
                          box={reportsTab}
                          onMarkReviewed={handleMarkReviewed}
                          markingId={markingId}
                          onDownload={handleDownloadPdf}
                          downloadingId={downloadingId}
                          forwardTargets={FORWARD_TARGETS}
                          onForward={handleForward}
                          forwardingId={forwardingId}
                        />
                      ))}
                    </div>
                  </div>
                ))}
              </div>
            ) : (
              <div className="divide-y divide-gray-100">
                {visibleReports.map((r) => (
                  <ReportRow
                    key={r.reportId}
                    r={r}
                    box={reportsTab}
                    onMarkReviewed={handleMarkReviewed}
                    markingId={markingId}
                    onDownload={handleDownloadPdf}
                    downloadingId={downloadingId}
                    forwardTargets={FORWARD_TARGETS}
                    onForward={handleForward}
                    forwardingId={forwardingId}
                  />
                ))}
              </div>
            )}
          </div>
        </div>

        {showGenerateModal && (
          <GenerateReportModal
            jurisdictionId={jurisdictionId}
            onClose={() => setShowGenerateModal(false)}
            onGenerated={handleReportGenerated}
          />
        )}

      </div>
    </>
  );
}
